application: autoproxy2pac
version: 3
runtime: python
api_version: 1

default_expiration: 1d

handlers:

- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)

- url: /static
  static_dir: static

- url: /facebox
  static_dir: static/facebox

- url: /tasks/.*
  script: main.py
  login: admin

- url: /_ah/admin(/.*)?
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: .*
  script: main.py

admin_console:
  pages:

  - name: Interactive Console
    url: /_ah/admin/interactive

  - name: Memcache Viewer
    url: /_ah/admin/memcache
